### PR TITLE
Remove mruby io dependency

### PR DESCRIPTION
**Pull request by i110**
Starting from 1.4.0, mruby bundles mruby-io

### CODE REVIEW

**Comment by take-cheeze** [comment]
mruby-io is still mrbgem in 1.4.
Overwrite it in build_config.rb instead.

**Comment by i110** [comment]
@take-cheeze Sorry I might not get your point, but https://github.com/iij/mruby-require/pull/23/commits/83270474cc9621ad8446f6eedc00d1a0a8b61275 can resolve the issue?

**Comment by take-cheeze** [comment]
Ah, sorry I missed some point too.
I think this should be kept to `iij/mruby-io` since this is iij's property and they seems to still use `iij/mruby-io`.
If you specify `gem core: 'mruby-io'` in your build_config.rb it will use the core mruby-io.
And from 1.4.1 it should use core mruby-io instead of mgem if not specified: https://github.com/mruby/mruby/commit/3dc8634d86b9abfce4c2eb1d394b6cd0e51fbd15

**Comment by i110** [comment]
Thank you for the clarification. 

> If you specify gem core: 'mruby-io' in your build_config.rb it will use the core mruby-io.

I see. I was breaking down some test failures, and I thought some differences between core and iij's one might be the cause of it. At that time I couldn't find any reasons to still use iij's one, but if iij people still want to use it I don't have any objections to it because I don't stuck with it now 😃

**Comment by tsahara** [comment]
Though we stick to an older version of mruby (1.3.0+ currently), it is recommended to use bundled mruby-io on mruby master.  Thank you for the patch and comments!

**Pull request merged**
